language: python
python:
  - "3.5"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - python3 -m unittest
  - coverage run --source -m unittest
after_success:
  - coveralls
